services:
  client:
    build:
      context: ..
      dockerfile: docker/client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - ../src:/app/src
    depends_on:
      - server

  server:
    build:
      context: ../server
      dockerfile: ../docker/server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=mongodb://mongodb:27017/gantt-chart
    volumes:
      - ../server/src:/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 